common:
  #work around travis encrypted string length limit
  href: <%= ENV['STORMPATH_URL'] || "https://3HSCDR9GU1PAI9XPZ4RPLXRVO:#{ENV['STORMPATH_SECRET']}@api.stormpath.com/v1/applications/vmuSPsTBRnGBQ6JaxxeuhA" %>
  #likely redundant, check if can be removed
  application: https://api.stormpath.com/v1/applications/vmuSPsTBRnGBQ6JaxxeuhA

development:
  root: https://api.stormpath.com/v1/directories/CuRnLT-YTO6SZ808ndy9jQ

test:
  root: https://api.stormpath.com/v1/directories/ZR_JlCc0QlKaUdD5-yYAhA

production:
  root: https://api.stormpath.com/v1/directories/zqlLJ_SjTCmoh10Nl3oTIg
